name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install

      - name: Build Archive (no signing)
        run: |
          xcodebuild \
          -workspace taqua_app.xcworkspace \
          -scheme taqua_app \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          CODE_SIGNING_ALLOWED=NO \
          archive \
          -archivePath build/taqua_app.xcarchive

      - name: Create IPA folder
        run: mkdir -p build/ipa

      - name: Zip app manually
        run: |
          cd build
          mkdir Payload
          cp -r taqua_app.xcarchive/Products/Applications/*.app Payload/
          zip -r ipa/taqua_app.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: taqua-ipa
          path: build/ipa
